### ISSUE TITLE
note

### ISSUE THREAD

**Issue by nabilgames** [3kh0/retro-bowl#1]
thanks for making this, i will add it to my new website but also i will keep your credits because your github links are blocked at my school.

**Comment by nabilgames** [comment]
> ok, can we chat some time? I want to figure out a workaround for your school! I got discord and email I guess

Okay ,, i will dm u on discord, im tryna unblock some websites 4 my school so i can give the rightful credits, but i dont take any credit for them

**Comment by 3kh0** [comment]
> > ok, can we chat some time? I want to figure out a workaround for your school! I got discord and email I guess
> 
> Okay ,, i will dm u on discord, im tryna unblock some websites 4 my school so i can give the rightful credits, but i dont take any credit for them

ok, you should post your discord details on your profile tho. I have more to talk with you

**Comment by 3kh0** [comment]
Inactivty
